import Head from "next/head";
import React, { useEffect, useState } from "react";
import PokeScrow from "../styles/styledsPokedex/PokeScrow";
import Link from "next/link";
import PokesmonsScrow from "../styles/styledsPokedex/PokesmonsScrow";
import Logo from "../styles/styledsHome/Logo";
import Paragraphy from "../styles/styledsPokedex/Paragraphy";
import InputSearch from "../styles/styledsPokedex/InputSearch";
import Card from "../components/Card";

type PokeProps = {
  id: string;
  number: string;
  url: string;
  name: string;
  image: string;
  fetchedAt: string;
  attacks: {
    special: Array<{
      name: string;
      type: string;
      damage: number;
    }>
  }
};

const pokedex = () => {
  const [pokemons, setPokemons] = useState<Array<PokeProps>>([]);

  useEffect(() => {
    const getData = async () => {
      try {
        const maxPokemons = 100;
        const url = 'https://pokeapi.co/api/v2/pokemon';

        const res = await fetch(`${url}/?limit=${maxPokemons}`);
        const data = await res.json();
        console.log(data.results);

        data.results.forEach((obj: any, idx: number) => obj.id = idx + 1);

        setPokemons(data.results);
      }
      catch (e) {
        console.log(`Error: ${e}`);
      }
    };

    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Dash - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>

      </section>

      <main>
        <PokesmonsScrow>
          <Link href={'/'}>Home</Link>
          <Logo val/>

          <Paragraphy>Everything you wanted to know about<br /> your favorite pocket monster!</Paragraphy>

          <InputSearch/>

          <hr />

          <PokeScrow>
            <ul>
              {pokemons.map(poke => (
                <li key={poke.id}>{`#${poke.id}`} - {poke.name}</li>
              ))}
            </ul>
          </PokeScrow>
        </PokesmonsScrow>

        OI
      </main>
    </div>
  );
};

export default pokedex;
